version: 0.2
phases:
  install:
    runtime-version:
      golang: 1.19
  pre_build:
    commands:
      - go mod tidy
  build:
    commands:
      - go mod build
  post_build:
    commands:
      - go mod publish
artifacts:
  files:
    - "**/*"
  